management:
  endpoints:
    enabled-by-default: true
  info:
    enabled: true
server:
  port: 5000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true